In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

### Logistic regression


In [3]:

lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9555555555555556

### svm

In [4]:
svm = SVC(kernel="poly")
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

### Random forset

In [5]:

rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9611111111111111

### KFold cross validation

**Basic example**

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=10)
kf

KFold(n_splits=10, random_state=None, shuffle=False)

In [7]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [8]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=10)

scores_logistic = []
scores_svm = []
scores_rf = []



In [22]:
for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(kernel="poly"), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [23]:
lr=np.array(scores_logistic)
lr

array([0.91111111, 0.93888889, 0.89444444, 0.86666667, 0.94444444,
       0.97222222, 0.97777778, 0.94972067, 0.8603352 , 0.94413408,
       0.91111111, 0.93888889, 0.89444444, 0.86666667, 0.94444444,
       0.97222222, 0.97777778, 0.94972067, 0.8603352 , 0.94413408,
       0.91111111, 0.93888889, 0.89444444, 0.86666667, 0.94444444,
       0.97222222, 0.97777778, 0.94972067, 0.8603352 , 0.94413408])

In [24]:
print(lr.mean())

0.9259745499689633


In [25]:
svc=np.array(scores_svm)
svc

array([0.43888889, 0.57777778, 0.46666667, 0.38888889, 0.47222222,
       0.4       , 0.50555556, 0.57541899, 0.55865922, 0.43575419,
       0.43888889, 0.57777778, 0.46666667, 0.38888889, 0.47222222,
       0.4       , 0.50555556, 0.57541899, 0.55865922, 0.43575419,
       0.96111111, 1.        , 0.93333333, 0.98333333, 0.99444444,
       0.99444444, 0.98888889, 0.99441341, 0.96089385, 0.96648045])

In [26]:
svc.mean()

0.647233602317401

In [27]:
rf=np.array(scores_rf)
rf

array([0.90555556, 0.97777778, 0.92222222, 0.92777778, 0.96111111,
       0.96111111, 0.97777778, 0.97206704, 0.90502793, 0.91620112,
       0.92222222, 0.96111111, 0.94444444, 0.93888889, 0.96111111,
       0.96666667, 0.95555556, 0.98324022, 0.94413408, 0.92178771,
       0.9       , 0.97222222, 0.92777778, 0.91666667, 0.95555556,
       0.97222222, 0.97777778, 0.96648045, 0.92178771, 0.94413408])

In [28]:
rf.mean()

0.946013863025036

### cross_val_score function

In [29]:
#does the exact same thing as above bit of code

In [30]:
from sklearn.model_selection import cross_val_score

In [32]:
lr_2=cross_val_score(LogisticRegression(), digits.data, digits.target,cv=10)

C:\Users\CHAITANYA\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\CHAITANYA\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logi

In [33]:
lr_2_2=np.array(lr_2)

In [34]:
lr_2_2.mean()

0.928193668528864

In [38]:
svm_2=cross_val_score(SVC(kernel="rbf"), digits.data, digits.target,cv=10)

In [39]:
svm_2_2=np.array(svm_2)

In [40]:
svm_2_2.mean()

0.9699503414028554

In [41]:
rf_2=cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target,cv=10)

In [42]:
rf_2_2=np.array(rf_2)

In [43]:
rf_2_2.mean()

0.9449068901303537

### Parameter tunning using k fold cross validation

In [44]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8803320918684048

In [45]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9443730602110489

In [46]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.941018001241465

In [47]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9460024829298572

In [50]:
scores5 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target, cv=10)
np.average(scores5)

0.9504748603351955

In [51]:
scores6 = cross_val_score(RandomForestClassifier(n_estimators=100),digits.data, digits.target, cv=10)
np.average(scores6)

0.9510273122284294

### fro svm kernels

In [52]:
score1 = cross_val_score(SVC(kernel="rbf"),digits.data, digits.target, cv=10)
np.average(score1)

0.9699503414028554

In [54]:
score2 = cross_val_score(SVC(kernel="poly"),digits.data, digits.target, cv=10)
np.average(score2)

0.9777343265052763

In [56]:
score3 = cross_val_score(SVC(kernel="linear"),digits.data, digits.target, cv=10)
np.average(score3)

0.9604872749844816

In [57]:
score4 = cross_val_score(SVC(kernel="sigmoid"),digits.data, digits.target, cv=10)
np.average(score4)

0.8848013656114215