In [15]:
def number_of_lines():
    fhand = open('/cxldata/datasets/project/mbox-short.txt')
    inp = fhand.read()
    count=0
    for l in inp:
        if l=="\n":
            
            count=count+1
    
    return count
    
    fhand.close()

In [16]:
number_of_lines()

1910

In [2]:
count_number_of_lines()

27

In [3]:
def count_number_of_lines():
    fhand = open("/cxldata/datasets/project/mbox-short.txt", "r")
    count = 0
    for line in fhand:
        line = line.rstrip()
        if line.startswith('Subject:'):
            count = count + 1
    return count

In [34]:
def average_spam_confidence():
    fhand = open("/cxldata/datasets/project/mbox-short.txt", "r")
    sum_spam=0
   # f=fhand.read()
    count=0
    for line in fhand:
        if line.startswith("X-DSPAM-Confidence:"):
            count=count+1
            sum_spam=sum_spam+(float(line.split(':')[1]))
    
    return sum_spam/count


In [35]:
average_spam_confidence()

0.7507185185185187

In [61]:
def find_email_sent_days():
    fhand = open("/cxldata/datasets/project/mbox-short.txt", "r")
    count=0
    g=fhand.read()
    days_of_the_week={}
    for line in fhand:
        line=line.rstrip()
        line_split=line.split()
        if line.startswith('From'):
            print(line_split[2])
            days_of_the_week[line_split[2]]=days_of_the_week.get[line_split[2],0]+1
            

        
       
    fhand.close()
    #print(count)
    return days_of_the_week
    
    
    
    
    

In [62]:
find_email_sent_days()

{}

In [80]:
    fhand = open("/cxldata/datasets/project/mbox-short.txt", "r")
    count=0
    g=fhand.read()
    days_of_the_week={}
    for line in fhand:
        line=line.rstrip()
        #line_split=line.split()
        if line.startswith('From'):
            count=count+1

In [81]:
print(count)

0


In [7]:
import numpy as np

In [8]:
list =[1,2,3]

In [9]:
list_array=np.array(list)

In [10]:
tup=(1,2,3)

In [11]:
my_tup_array=np.array(tup)

In [18]:
tup_dim=(3,4)

In [19]:
my_zeros_array=np.zeros(tup_dim,dtype=np.int16)

In [20]:
my_ones_array=np.ones(tup_dim,dtype=np.int16)

In [21]:
my_seven_array=np.full(tup_dim,7,dtype=np.int16)

In [22]:
my_identity_array = np.identity(4, dtype=np.float64)

In [47]:
my_rand_array=np.random.rand(3,4)

In [48]:
my_rand_array


array([[0.55839121, 0.93813016, 0.6939076 , 0.87541563],
       [0.65355416, 0.31781983, 0.05604889, 0.43993034],
       [0.93390437, 0.79744099, 0.08937215, 0.45755853]])

In [50]:
my_uninitialized_array=np.empty(tup_dim)

In [60]:
my_uninitialized_array


array([[0.55839121, 0.93813016, 0.6939076 , 0.87541563],
       [0.65355416, 0.31781983, 0.05604889, 0.43993034],
       [0.93390437, 0.79744099, 0.08937215, 0.45755853]])

In [62]:
my_range_array=np.arange(10,30,5)

In [63]:
my_range_array

array([10, 15, 20, 25])

In [64]:
my_spaced_array=np.linspace(0,5/3,6)

In [74]:
array_A = np.array([ [3,4,6], [0,8,1] ])

In [76]:
array_A.ndim

2

In [77]:
array_A.shape

(2, 3)

In [79]:
array_A.size

6

In [80]:
array_A.dtype

dtype('int64')

In [81]:
array_A.itemsize

8

In [115]:
import os
import pandas as pd
import numpy as np

In [146]:
my_arr=np.array([[1,2,3,4],[5,6,7,8]])
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [155]:
my_arr.resize((3,4),refcheck=False)

In [156]:
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0]])

In [160]:
my_first_arr=np.array([1,2,3,4,5,6,7,8])

In [163]:
my_new_arr=my_first_arr.reshape((2,4))

In [164]:
my_first_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [165]:
my_new_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [166]:
my_second_arr=np.array([0,1,2,3,4,5,6,7,8])

In [167]:
my_updated_arr=my_second_arr.reshape((-1,3))

In [168]:
my_updated_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [169]:
my_second_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [179]:
import numpy as np
from sklearn.datasets import load_sample_image

In [180]:
china = load_sample_image("china.jpg")

In [181]:
china.shape

(427, 640, 3)

In [182]:
china

array([[[174, 201, 231],
        [174, 201, 231],
        [174, 201, 231],
        ...,
        [250, 251, 255],
        [250, 251, 255],
        [250, 251, 255]],

       [[172, 199, 229],
        [173, 200, 230],
        [173, 200, 230],
        ...,
        [251, 252, 255],
        [251, 252, 255],
        [251, 252, 255]],

       [[174, 201, 231],
        [174, 201, 231],
        [174, 201, 231],
        ...,
        [252, 253, 255],
        [252, 253, 255],
        [252, 253, 255]],

       ...,

       [[ 88,  80,   7],
        [147, 138,  69],
        [122, 116,  38],
        ...,
        [ 39,  42,  33],
        [  8,  14,   2],
        [  6,  12,   0]],

       [[122, 112,  41],
        [129, 120,  53],
        [118, 112,  36],
        ...,
        [  9,  12,   3],
        [  9,  15,   3],
        [ 16,  24,   9]],

       [[116, 103,  35],
        [104,  93,  31],
        [108, 102,  28],
        ...,
        [ 43,  49,  39],
        [ 13,  21,   6],
        [ 15,  24,   7]]

In [183]:
image=china[150:220,130:250]

In [184]:
image.shape

(70, 120, 3)

In [185]:
height, width, channels = image.shape

In [187]:
image_grayscale = image.mean(axis=2).astype(np.float32)

In [188]:
image_grayscale.shape

(70, 120)

In [190]:
images=image_grayscale.reshape(1, height, width, 1)

In [191]:
images.shape

(1, 70, 120, 1)

In [192]:
images.ndim

4

In [2]:
import numpy as np
my_orig_arr=np.array([1,15,3,9,26,7,89,12])


In [3]:
my_rev_arr=my_orig_arr[::-1]

In [4]:
my_rev_arr

array([12, 89,  7, 26,  9,  3, 15,  1])

In [5]:
my_orig_arr2=np.array([2,9,17,13,1,4,20])

In [6]:
my_orig_arr2[2 : 5] = -6

In [7]:
print(my_orig_arr2)

[ 2  9 -6 -6 -6  4 20]


In [8]:
arr = [1, 3, 5, 10, 4, 15]
arr[1 : 4]  = -3

TypeError: can only assign an iterable

In [10]:
apple=np.array([1,8,23,3,18,91,7,15])

In [11]:
apple_slice=apple[1:4]

In [12]:
print(apple_slice)

[ 8 23  3]


In [13]:
print(apple)

[ 1  8 23  3 18 91  7 15]


In [14]:
apple_slice[1] = 99999
print(apple_slice)

[    8 99999     3]


In [15]:
apple_slice_new = apple[2 : 5].copy()

In [16]:
apple_slice_new[1] = 222222

In [17]:
print(apple_slice_new)

[ 99999 222222     18]


In [26]:
from sklearn.datasets import load_sample_image

In [27]:
china = load_sample_image("china.jpg")

In [28]:
portion=china[120:250,110:230]

In [29]:
print(portion.ndim)

3


In [34]:
my_multi_arr=np.arange(20).reshape((4,5))

In [35]:
my_multi_arr_portion = my_multi_arr[2:4,2:5]

In [36]:
print(my_multi_arr_portion)

[[12 13 14]
 [17 18 19]]


In [43]:
my_2d_arr=np.arange(20).reshape(4,5)

In [44]:
my_1d_arr=my_2d_arr.ravel()

In [47]:
print(my_1d_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [54]:
a_arr = np.array([60,70,80,90])
b_arr = np.arange(4)

In [55]:
c_arr=a_arr+b_arr

In [56]:
print(c_arr)

[60 71 82 93]


In [57]:
d_arr = np.array([60,70,80,90])
e_arr = np.arange(4)

In [58]:
f_arr=d_arr-e_arr

In [59]:
print(f_arr)

[60 69 78 87]


In [76]:
A_arr = np.array([ [ 5,9], [4, 7] ])
B_arr = np.array( [ [2, 8], [1, 6] ] )

In [77]:
M_arr=A_arr*B_arr

In [78]:
print(M_arr)

[[10 72]
 [ 4 42]]


In [79]:
C_arr = np.array([ [ 5,9], [4, 7] ])
D_arr = np.array( [ [2, 8], [1, 6] ] )

In [80]:
P_arr=np.dot(C_arr,D_arr)

In [81]:
print(P_arr)

[[19 94]
 [15 74]]


In [98]:
R_div = np.array([ [ 25,65], [40, 14] ])
S_div = np.array( [ [2, 10], [4, 5] ] )

In [99]:
T_div=R_div/S_div

In [100]:
print(T_div)

[[12.5  6.5]
 [10.   2.8]]


In [101]:
R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array( [ [2, 10], [8, 3] ] )

In [102]:
T_int_div=R_int_div//S_int_div

In [103]:
print(T_int_div)

[[12  6]
 [ 5 23]]


In [104]:
R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array( [ [2, 10], [8, 3] ] )

In [105]:
T_mod=R_mod%S_mod

In [106]:
print(T_mod)

[[0 5]
 [0 1]]


In [125]:
R_exp= np.array([ [ 4, 2], [3, 4 ] ] )
S_exp = np.array( [ [2, 10], [4, 5] ] )

In [126]:

T_exp=R_exp**S_exp

In [127]:
print(T_exp)

[[  16 1024]
 [  81 1024]]


In [136]:
U = np.array([ [ 22, 45], [90, 4 ] ] )

In [137]:
print(U<45)

[[ True False]
 [False  True]]


In [3]:
import numpy as np
X_stat=np.array([ [ 1, 2, 3], [ 4, -5, 6] ])


In [4]:
print("mean = ",X_stat.mean())
print("Variance = ",X_stat.var())
print("Standard Deviation = ",X_stat.std())
print("max = ",X_stat.min())
print("m = ",X_stat.max())
print("sum = ",X_stat.sum())
print("product = ",X_stat.prod())

mean =  1.8333333333333333
Variance =  11.805555555555557
Standard Deviation =  3.435921354681384
max =  -5
m =  6
sum =  11
product =  -720


In [16]:
Y = np.arange(24).reshape(2,3,4)

print(Y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [20]:
Y.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [21]:
Y.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [22]:
Y.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [30]:
Z=np.arange(18).reshape(2,3,3)
print(Z)
print(Z.sum(axis=2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[ 3 12 21]
 [30 39 48]]


In [36]:
N=np.arange(6).reshape(3,2)
print(N)
print("Transpose =",N.T)

[[0 1]
 [2 3]
 [4 5]]
Transpose = [[0 2 4]
 [1 3 5]]


In [43]:
#Broadcasting rules when rank is not same of two arrays
Q = np.array( [ [ [1, 3 ] ] ] )
P = np.array( [ 5 ] )

S = Q + P

print(S)

[[[6 8]]]


In [44]:
#second rule-Arrays with a 1 along with a particular 
#dimension act as if they had the size of the array
#with the largest shape along that dimension. 
#The value of the array element is repeated along that 
#dimension



In [46]:
X_broad=np.ones((3,3))
print(X_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [47]:
Y_broad=np.arange(3)
print(Y_broad)

[0 1 2]


In [48]:
    Z_broad=X_broad+Y_broad

In [49]:
print(Z_broad)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
